[package]
name = "toylang_compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
# export LLVM_SYS_180_PREFIX=/opt/homebrew/opt/llvm@18
inkwell = { version = "0.5.0", features = ["llvm15-0"] }

